name: where_not_null
description: A single extension on Iterable<T?> to convert it to Iterable<T>
version: 1.0.2
homepage: https://github.com/Ampless/where_not_null

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
