name: where_not_null
description: A single extension on Iterable<T?> to convert it to Iterable<T>
version: 1.0.0
homepage: https://github.com/Ampless/where_not_null

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
